<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://tempuri.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:http="http://schemas.microsoft.com/ws/06/2004/policy/http" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" targetNamespace="http://tempuri.org/" name="IAuthorService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
      <xs:import namespace="http://schemas.datacontract.org/2004/07/SampleWSDLApp" />
      <xs:element name="GetMethod">
        <xs:complexType>
          <xs:sequence />
        </xs:complexType>
      </xs:element>
      <xs:element name="GetMethodResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="GetMethodResult" nillable="true" xmlns:q1="http://schemas.datacontract.org/2004/07/SampleWSDLApp" type="q1:Author" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="AddItem">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="author" nillable="true" xmlns:q2="http://schemas.datacontract.org/2004/07/SampleWSDLApp" type="q2:Author" />
            <xs:element minOccurs="1" name="exampleclass" nillable="true" xmlns:q3="http://schemas.datacontract.org/2004/07/SampleWSDLApp" type="q3:exampleclass" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="AddItemResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="AddItemResult" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Addnumbers">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="a" type="xs:int" />
            <xs:element minOccurs="1" name="b" type="xs:int" />
            <xs:element minOccurs="1" name="author" nillable="true" xmlns:q4="http://schemas.datacontract.org/2004/07/SampleWSDLApp" type="q4:Author" />
            <xs:element minOccurs="1" name="bookdetails" nillable="true" xmlns:q5="http://schemas.datacontract.org/2004/07/SampleWSDLApp" type="q5:Bookdetails" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="AddnumbersResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="AddnumbersResult" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
      <xs:element name="anyType" nillable="true" type="xs:anyType" />
      <xs:element name="anyURI" nillable="true" type="xs:anyURI" />
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
      <xs:element name="boolean" nillable="true" type="xs:boolean" />
      <xs:element name="byte" nillable="true" type="xs:byte" />
      <xs:element name="dateTime" nillable="true" type="xs:dateTime" />
      <xs:element name="decimal" nillable="true" type="xs:decimal" />
      <xs:element name="double" nillable="true" type="xs:double" />
      <xs:element name="float" nillable="true" type="xs:float" />
      <xs:element name="int" nillable="true" type="xs:int" />
      <xs:element name="long" nillable="true" type="xs:long" />
      <xs:element name="QName" nillable="true" type="xs:QName" />
      <xs:element name="short" nillable="true" type="xs:short" />
      <xs:element name="string" nillable="true" type="xs:string" />
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort" />
      <xs:element name="char" nillable="true" type="tns:char" />
      <xs:simpleType name="char">
        <xs:restriction base="xs:int" />
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration" />
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid" />
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName" />
      <xs:attribute name="Id" type="xs:ID" />
      <xs:attribute name="Ref" type="xs:IDREF" />
    </xs:schema>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SampleWSDLApp" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/SampleWSDLApp" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
      <xs:import namespace="http://schemas.datacontract.org/2004/07/System" />
      <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
      <xs:complexType name="Author" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
        <xs:sequence>
          <xs:element minOccurs="0" name="Address" nillable="true" type="tns:Address" />
          <xs:element minOccurs="0" name="FirstName" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="Id" type="xs:int" />
          <xs:element minOccurs="0" name="LastName" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="Phonenumber" nillable="true" type="xs:string" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="Author" nillable="true" type="tns:Author" />
      <xs:complexType name="Address" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
        <xs:sequence>
          <xs:element minOccurs="0" name="city" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="state" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="streetdetails" nillable="true" type="tns:Streetdetails" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="Address" nillable="true" type="tns:Address" />
      <xs:complexType name="Streetdetails" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
        <xs:sequence>
          <xs:element minOccurs="0" name="Doorno" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="Streetname" nillable="true" type="xs:string" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="Streetdetails" nillable="true" type="tns:Streetdetails" />
      <xs:complexType name="exampleclass" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
        <xs:sequence>
          <xs:element minOccurs="0" name="Age" type="xs:int" />
          <xs:element minOccurs="0" name="DateOfBirth" type="xs:dateTime" />
          <xs:element minOccurs="0" name="DateOfJoining" type="xs:dateTime" />
          <xs:element minOccurs="0" name="FirstName" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="GPA" type="xs:double" />
          <xs:element minOccurs="0" name="Height" type="xs:short" />
          <xs:element minOccurs="0" name="HexBinaryData" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="IsActive" type="xs:boolean" />
          <xs:element minOccurs="0" name="Language" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="LastName" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="NCName" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="Name" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="NegativeInteger" type="xs:int" />
          <xs:element minOccurs="0" name="NonNegativeInteger" type="xs:int" />
          <xs:element minOccurs="0" name="NonPositiveInteger" type="xs:int" />
          <xs:element minOccurs="0" name="PhoneNumber" type="xs:long" />
          <xs:element minOccurs="0" name="PositiveInteger" type="xs:int" />
          <xs:element minOccurs="0" name="Salary" type="xs:decimal" />
          <xs:element minOccurs="0" name="SignedByte" type="xs:byte" />
          <xs:element minOccurs="0" name="UnsignedByte" type="xs:byte" />
          <xs:element minOccurs="0" name="UnsignedInt" type="xs:unsignedInt" />
          <xs:element minOccurs="0" name="UnsignedLong" type="xs:unsignedLong" />
          <xs:element minOccurs="0" name="UnsignedShort" type="xs:unsignedShort" />
          <xs:element minOccurs="0" name="Website" type="xs:anyURI" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="exampleclass" nillable="true" type="tns:exampleclass" />
      <xs:complexType name="Bookdetails" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
        <xs:sequence>
          <xs:element minOccurs="0" name="Bookname" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="Bookprice" nillable="true" type="xs:string" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="Bookdetails" nillable="true" type="tns:Bookdetails" />
    </xs:schema>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
      <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IAuthorService_GetMethod_InputMessage">
    <wsdl:part name="parameters" element="tns:GetMethod" />
  </wsdl:message>
  <wsdl:message name="IAuthorService_GetMethod_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetMethodResponse" />
  </wsdl:message>
  <wsdl:message name="IAuthorService_AddItem_InputMessage">
    <wsdl:part name="parameters" element="tns:AddItem" />
  </wsdl:message>
  <wsdl:message name="IAuthorService_AddItem_OutputMessage">
    <wsdl:part name="parameters" element="tns:AddItemResponse" />
  </wsdl:message>
  <wsdl:message name="IAuthorService_Addnumbers_InputMessage">
    <wsdl:part name="parameters" element="tns:Addnumbers" />
  </wsdl:message>
  <wsdl:message name="IAuthorService_Addnumbers_OutputMessage">
    <wsdl:part name="parameters" element="tns:AddnumbersResponse" />
  </wsdl:message>
  <wsdl:portType name="IAuthorService">
    <wsdl:operation name="GetMethod">
      <wsdl:input wsam:Action="http://tempuri.org/IAuthorService/GetMethod" message="tns:IAuthorService_GetMethod_InputMessage" />
      <wsdl:output wsam:Action="http://tempuri.org/IAuthorService/GetMethodResponse" message="tns:IAuthorService_GetMethod_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="AddItem">
      <wsdl:input wsam:Action="http://tempuri.org/IAuthorService/AddItem" message="tns:IAuthorService_AddItem_InputMessage" />
      <wsdl:output wsam:Action="http://tempuri.org/IAuthorService/AddItemResponse" message="tns:IAuthorService_AddItem_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="Addnumbers">
      <wsdl:input wsam:Action="http://tempuri.org/IAuthorService/Addnumbers" message="tns:IAuthorService_Addnumbers_InputMessage" />
      <wsdl:output wsam:Action="http://tempuri.org/IAuthorService/AddnumbersResponse" message="tns:IAuthorService_Addnumbers_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IAuthorService" type="tns:IAuthorService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetMethod">
      <soap:operation soapAction="http://tempuri.org/IAuthorService/GetMethod" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddItem">
      <soap:operation soapAction="http://tempuri.org/IAuthorService/AddItem" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Addnumbers">
      <soap:operation soapAction="http://tempuri.org/IAuthorService/Addnumbers" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="IAuthorService">
    <wsdl:port name="BasicHttpBinding_IAuthorService" binding="tns:BasicHttpBinding_IAuthorService">
      <soap:address location="http://localhost:5270/Authorservice.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>